keys:
  - &zanbee  age132epu6cpy3983s2wpq684u6q2x4uhra2kh45t73zv6uszfuhdfpqczl6v0
  - &bifrost age1fgrckwqj6acu42pucsuknneva7cupph4suhddvcw9ek25mrv4srqpxsh32
  - &vm      age1dvjf4kcmwd708xvx8y3mscypxpv2cu7sggmkve2492g0xwzzyavs2zgr5c
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *zanbee
          - *bifrost
          - *vm
